// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoDeAprendizajeP3.Infrastruture.Persistence.Contexts;

#nullable disable

namespace ProyectoDeAprendizajeP3.Infrastruture.Persistence.Migrations
{
    [DbContext(typeof(InvestmentContext))]
    [Migration("20260428222814_AlterPasswordColumInUserEntityToAddMoreLenght")]
    partial class AlterPasswordColumInUserEntityToAddMoreLenght
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.AssetHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HistoryValueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetHistorical", (string)null);
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes", (string)null);
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.InvestmentAsset", b =>
                {
                    b.Property<int>("InvestmentPortfolioId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("associationdate")
                        .HasColumnType("datetime2");

                    b.HasKey("InvestmentPortfolioId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("InvestmentAssets", (string)null);
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.InvestmentPortfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("InvestmentPortfolios", (string)null);
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.Asset", b =>
                {
                    b.HasOne("ProyectoDeAprendizajeP3.Core.Domain.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.AssetHistory", b =>
                {
                    b.HasOne("ProyectoDeAprendizajeP3.Core.Domain.Entities.Asset", "Assets")
                        .WithMany("AssetHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.InvestmentAsset", b =>
                {
                    b.HasOne("ProyectoDeAprendizajeP3.Core.Domain.Entities.Asset", "asset")
                        .WithMany("investmentAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoDeAprendizajeP3.Core.Domain.Entities.InvestmentPortfolio", "investmentPortfolio")
                        .WithMany("investmentAssets")
                        .HasForeignKey("InvestmentPortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asset");

                    b.Navigation("investmentPortfolio");
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.InvestmentPortfolio", b =>
                {
                    b.HasOne("ProyectoDeAprendizajeP3.Core.Domain.Entities.User", "user")
                        .WithMany("investmentPortfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetHistories");

                    b.Navigation("investmentAssets");
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.InvestmentPortfolio", b =>
                {
                    b.Navigation("investmentAssets");
                });

            modelBuilder.Entity("ProyectoDeAprendizajeP3.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("investmentPortfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
